# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import nba_player_news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', enumfields.fields.EnumField(enum=nba_player_news.models.SubscriptionPlatformEnum, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_player_news.SubscriptionPlatform'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('platform', 'identifier')]),
        ),
    ]
