# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_player_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='platform',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook')], max_length=50),
        ),
    ]
