# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_player_news', '0002_auto_20170503_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='unsubscribed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
