# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_player_news', '0003_subscription_unsubscribed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=2048)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_player_news.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAttemptResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
                ('response', models.TextField(max_length=2048)),
                ('subscription_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_player_news.SubscriptionAttempt')),
            ],
        ),
    ]
